apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

# Pin the image tag centrally (optional)
images:
  - name: nginx
    newTag: 1.27-alpine