apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize that the dev overlay should place everything in the "dev" namespace
namespace: dev

# The dev overlay references the base folder
resources:
  - ../base